FROM node:22-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./
COPY client/package.json ./client/
COPY shared/package.json ./shared/

RUN npm ci

COPY client/ ./client/
COPY shared/ ./shared/

RUN npm run build --workspace=@shared/types
RUN npm run build --workspace=split-app-client


FROM nginx:alpine AS runner

COPY --from=builder /app/client/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]