FROM node:22-alpine
WORKDIR /app

COPY package.json package-lock.json tsconfig.json ./

COPY client/package.json ./client/
COPY server/package.json ./server/
COPY shared/package.json ./shared/

RUN npm ci

COPY server/ ./server/
COPY shared/ ./shared/

RUN npm run build --workspace=@shared/types

WORKDIR /app

CMD ["npx", "concurrently", "--kill-others", "--names", "shared,server", "npm:dev:shared", "npm:dev:server"]