apiVersion: v1
kind: Service
metadata:
  name: server
  namespace: split-app
  labels:
    app.kubernetes.io/name: split-app-server
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: split-app
spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/name: split-app-server
    app.kubernetes.io/component: backend

  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP